export {INSERT_API} from './endpoints'
export {GET_CONFIG_API} from './endpoints'
export {getCategories} from './getCategories'
export {CATEGORY_DATA_API} from './endpoints'
export {FRONTEND_GITHUB_REPO} from './url'
export {RUN_POLITO_WEBSITE} from './url'
export {BACKEND_GITHUB_REPO} from './url'